tap "homebrew/bundle"
tap "robotsandpencils/made"

## CLI
brew "mas"
#brew "libusbmuxd", args: ["HEAD"]
#brew "libimobiledevice", args: ["HEAD"]
#brew "ideviceinstaller"
#brew "ios-deploy"
brew "robotsandpencils/made/xcodes"

## font
cask "font-hack-nerd-font"

## Apps
cask "google-japanese-ime"
cask "sf-symbols"
# cask "kindle"
cask "alfred"
cask "postman"
cask "proxyman"
# cask "discord"
cask "brave-browser"
cask "karabiner-elements"
cask "iterm2"
cask "warp"
cask "rapidapi"
cask "tower"
cask "transmit"
cask "charles"
cask "vlc"
cask "docker"
cask "google-chrome"
cask "visual-studio-code"

## optional
#mas "1Password", id: 443987910
#mas "RunCat", id: 1429033973
#mas "TweetDeck", id: 485812721
#mas "Spark", id: 1176895641
#mas "LINE", id: 539883307
