#----- settings for oh-my-zsh -----#

# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

# Path to your Oh My Zsh installation.
export ZSH="$HOME/.oh-my-zsh"
# See https://github.com/ohmyzsh/ohmyzsh/wiki/Themes
ZSH_THEME="powerlevel10k/powerlevel10k"
plugins=(git zsh-autosuggestions zsh-syntax-highlighting web-search)
source $ZSH/oh-my-zsh.sh
# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh


#----- import other zsh settings -----#

zsh_dir="$HOME"/.config/zsh
shoichi_dir="$zsh_dir"/shoichi

os_type=$(uname)
case "$os_type" in
    Linux)
        source $shoichi_dir/config-linux.zsh
        ;; 
    Darwin)
        source $shoichi_dir/config-osx.zsh
        ;;
    CYGWIN*|MINGW32*|MSYS*|MINGW*)
        ;;
    *)
        echo "Unknown OS: $os_type"
        ;;
esac

source $shoichi_dir/command-extensions.zsh

# for warp terminal settings
## change the font to Meslo Nerd Font
## https://docs.warp.dev/appearance/prompt#powerlevel10k