zsh_dir="$HOME"/.config/zsh
shoichi_dir="$zsh_dir"/shoichi
export EDITOR=nvim

# Enable emacs key bindings (Ctrl+A, Ctrl+E, etc.)
bindkey -e

#----- LANG -----#
export LANG=ja_JP.UTF-8
export LC_ALL=ja_JP.UTF-8

#----- setup prompt -----#
prompt="starship"
case $prompt in
    oh-my-zsh)
        source $shoichi_dir/oh-my-zsh.zsh
        ;;
    starship)
        export STARSHIP_CONFIG="$HOME/.config/starship/starship.toml"
        eval "$(starship init zsh)"
        ;;
    *)
        echo "Unknown prompt: $prompt"
        ;;
esac

#----- setup zsh on each systems -----#
os_type=$(uname)
case "$os_type" in
    Linux)
        source $shoichi_dir/config-linux.zsh
        ;; 
    Darwin)
        source $shoichi_dir/config-osx.zsh
        ;;
    CYGWIN*|MINGW32*|MSYS*|MINGW*)
        ;;
    *)
        echo "Unknown OS: $os_type"
        ;;
esac

#----- import other settings -----#
source $shoichi_dir/command-extensions.zsh
source $shoichi_dir/alias.zsh

# for warp terminal settings
## change the font to Meslo Nerd Font
## https://docs.warp.dev/appearance/prompt#powerlevel10k

